# YAML config
artifact_root : artifacts 

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Yonithe23/dataset/raw/refs/heads/master/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dirs: artifact_root/data_ingestion

